language: node_js
sudo: required
dist: trusty

env:
  global:
    - OCAML_VERSION=4.04
    - OPAMYES=true
    - UBUNTU_TRUSTY=1

matrix:
  include:
    - os: linux
      node_js: "10"
      env: DEPLOY=true
    - os: linux
      node_js: "10"
      env: TEST=true
    #- os: osx
    #  node_js: "10"
  allow_failures:
    - os: linux
      node_js: "10"
      env: TEST=true


install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - make init
  - if [ -n "$TEST" ]; then make test_init; fi
  - eval `opam config env`

script:
  - make
  - if [ -n "$TEST" ]; then make test; fi

deploy:
  skip_cleanup: true
  provider: script
  script: make publish-github
  on:
    condition: $DEPLOY = true
    all_branches: true

